[ShaderOverrideTessellation]
hash = 3f36f4a9b69e89bd
;partner = ba2ad61fa36ff709
handling = skip
$shader_type = 2

; 服装 Mod + 帧分析 dump（复用 CommandListSkin 的逻辑）
if $dump_skin_clothes
	dump = deferred_ctx_accurate share_dupes ps-t0 mono dds
	dump = deferred_ctx_accurate share_dupes ps-t3 mono dds
	analyse_options = deferred_ctx_accurate share_dupes dump_vb txt buf
	dump = deferred_ctx_accurate vs-cb2 txt buf
endif

if $costume_mods && (!frame_analysis || $dump_modded_meshes)
	; Enable body texture replacement by texture hash:
	checktextureoverride = ps-t0
	; Enable mesh replacement by either vertex or indexbuffer hash, must be done
	; after texture replacements, because this will replace the draw call:
	checktextureoverride = vb0
	checktextureoverride = ib
endif

run = CustomShaderTessellation

[CustomShaderTessellation]
topology = 3_control_point_patch_list
vs = ba2ad61fa36ff709-vs_replace.txt
hs = simple_tess_skin.hs.txt
ds = simple_tess_skin.ds.txt
ps = 3f36f4a9b69e89bd-ps_replace.txt
draw = from_caller
rasterizer_state_merge = 1
blend_state_merge = 1
x = 0.85
y = 4.0


